Cnt = int(input("Please enter the frequency : "))

for no in range(Cnt):
    print("Jay Ganesh...")

# Output:
# C:\Users\Priyanka\Desktop\Python_2024\20-04-2024>python Loop1.py
# Please enter the frequency : 5
# Jay Ganesh...
# Jay Ganesh...
# Jay Ganesh...
# Jay Ganesh...
# Jay Ganesh...